name: Release pipeline

on:
  pull_request:
    branches:
      - main
    tags-ignore:
      - 'v*' # this tag type is used for release pipelines

jobs:
  release-pipeline:

    environment: "STAGING"
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_STAGING_HOST }}
      DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_STAGING_TOKEN }}

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          echo "Launching unit tests"
          pytest tests

      - name: Run integration tests
        uses: databricks/run-notebook@v0
        with:
          local-notebook-path: notebooks/databricks_staging.py
          git-commit: ${{ github.event.pull_request.head.sha }}
          new-cluster-json: >
            {
              "num_workers": 1,
              "spark_version": "12.1.x-cpu-ml-scala2.12",
              "node_type_id": "i3.xlarge"
            }